/**
 * Unified projects database — every installation across all three product
 * lines, powering the /projects portfolio page (grid, filters, lightbox, and
 * its ItemList structured data).
 *
 * Each entry mirrors a case on its product's detail-page wall (lib/products.js)
 * or extends it with library footage that only the portfolio carries. Filter
 * facets are `industry` × `product` × `region`; `featured` marks flagship
 * installs the grid sorts to the front.
 *
 * Asset conventions follow the rest of the site: site-root-relative paths,
 * H.264 MP4 clips <8 MB with no audio, poster frames exported from the same
 * footage. `video: null` entries are photo-led (the Beijing Daxing reel is
 * deliberately unpublished — its screen content carries an Envato watermark —
 * so that project ships as a clean still only).
 *
 * Unnamed supplier footage (shop windows, demo rooms, generic clips) keeps
 * `location: null` rather than inventing a city; region reflects the install
 * market we can attest from the source material.
 */

const IMG = "/assets/images";
const VID = "/assets/videos";
const CASES = `${IMG}/cases`;
const MATRIX = `${IMG}/products/matrix-panel`;

export const INDUSTRIES = [
  { value: "retail", label: "Retail & Storefront" },
  { value: "hospitality", label: "Hospitality & F&B" },
  { value: "corporate", label: "Corporate & Office" },
  { value: "transportation", label: "Airport & Transit" },
  { value: "entertainment", label: "Entertainment & Events" },
  { value: "automotive", label: "Automotive" },
  { value: "financial", label: "Banking & Finance" },
  { value: "exhibition", label: "Exhibition & Showroom" },
];

export const REGIONS = [
  { value: "asia", label: "Asia Pacific" },
  { value: "europe", label: "Europe" },
  { value: "americas", label: "Americas" },
  { value: "middle-east", label: "Middle East & Africa" },
];

export const PRODUCT_TYPES = [
  { value: "crystal-film", label: "Crystal Film LED" },
  { value: "holographic", label: "Holographic LED" },
  { value: "soft-led-display", label: "Soft LED Display" },
];

export const PROJECTS = [
  /* ───────────────────────── Crystal Film LED Screen ───────────────────────── */
  {
    id: "coca-cola-experience",
    title: "Coca-Cola Experience Center",
    product: "crystal-film",
    productName: "Crystal Film LED Screen",
    model: "P6.25",
    industry: "exhibition",
    region: "asia",
    location: "China",
    video: `${VID}/case-cocacola.mp4`,
    poster: `${CASES}/case-coca-cola-experience-p625.jpg`,
    images: [`${CASES}/case-coca-cola-experience-p625.jpg`],
    description:
      "An immersive brand room wrapped corner-to-corner in transparent LED — effervescent red content surrounds the visitor while the glass keeps the space open and bright.",
    featured: true,
  },
  {
    id: "beijing-daxing-airport",
    title: "Beijing Daxing International Airport",
    product: "crystal-film",
    productName: "Crystal Film LED Screen",
    model: "P6.25",
    industry: "transportation",
    region: "asia",
    location: "Beijing · China",
    video: null,
    poster: `${CASES}/case-beijing-daxing-airport-p625.jpg`,
    images: [`${CASES}/case-beijing-daxing-airport-p625.jpg`],
    description:
      "A wall-to-wall transparent LED film installation at the rental-car concourse of Daxing's P1 parking structure — high-brightness content reads across the hall while daylight still passes through the glazing behind it.",
    featured: true,
  },
  {
    id: "gac-honda-dealership",
    title: "GAC Honda Dealership",
    product: "crystal-film",
    productName: "Crystal Film LED Screen",
    model: "P6",
    industry: "automotive",
    region: "asia",
    location: "Guangzhou · China",
    video: `${VID}/case-gac-honda.mp4`,
    poster: `${CASES}/case-honda-dealership-p6.jpg`,
    images: [`${CASES}/case-honda-dealership-p6.jpg`],
    description:
      "A dealership facade carries a welcome message across its full glazed front after dark, drawing the street in while the lit showroom and vehicles stay visible straight through the display.",
    featured: false,
  },
  {
    id: "xian-seg-plaza",
    title: "Xi'an SEG Plaza",
    product: "crystal-film",
    productName: "Crystal Film LED Screen",
    model: "P6.25",
    industry: "retail",
    region: "asia",
    location: "Xi'an · China",
    video: `${VID}/case-xian-seg.mp4`,
    poster: `${CASES}/case-xian-saga-mall-p625.jpg`,
    images: [`${CASES}/case-xian-saga-mall-p625.jpg`],
    description:
      "A storefront-wide transparent screen wraps the Helly Hansen window at Xi'an's SEG Plaza, running full-motion landscape content while shoppers still read straight through to the merchandise.",
    featured: false,
  },
  {
    id: "changan-auto-pavilion",
    title: "Changan Auto Glass Pavilion",
    product: "crystal-film",
    productName: "Crystal Film LED Screen",
    model: "P6.25",
    industry: "automotive",
    region: "asia",
    location: "China",
    video: `${VID}/case-changan-showroom.mp4`,
    poster: `${CASES}/case-changan-showroom-p625.jpg`,
    images: [`${CASES}/case-changan-showroom-p625.jpg`],
    description:
      "Changan's glass exhibition pavilion turns into a 4K media object at night — film bonded to every pane plays brand content in sync across the full structure.",
    featured: false,
  },
  {
    id: "japan-storefront",
    title: "Waterfront Storefront, Japan",
    product: "crystal-film",
    productName: "Crystal Film LED Screen",
    model: "P6.25",
    industry: "retail",
    region: "asia",
    location: "Japan",
    video: `${VID}/case-japan.mp4`,
    poster: `${CASES}/case-japan-storefront-p625.jpg`,
    images: [`${CASES}/case-japan-storefront-p625.jpg`],
    description:
      "A wrap-around transparent display brings an ocean scene to a Japanese waterfront storefront at night — luminous content on three faces of glass that still reads as a clear window by day.",
    featured: false,
  },
  {
    id: "uzbekistan-mall",
    title: "Shopping Mall Atrium",
    product: "crystal-film",
    productName: "Crystal Film LED Screen",
    model: "P8",
    industry: "retail",
    region: "asia",
    location: "Uzbekistan",
    video: `${VID}/case-uzbekistan.mp4`,
    poster: `${CASES}/case-uzbekistan-mall-p8.jpg`,
    images: [`${CASES}/case-uzbekistan-mall-p8.jpg`],
    description:
      "A transparent LED storefront in Uzbekistan floats a product hero in mid-air — a sneaker suspended in blue smoke across the glass — pulling the concourse in while the shop behind stays fully visible.",
    featured: false,
  },
  {
    id: "hongkong-yoga-studio",
    title: "Yoga Studio Window",
    product: "crystal-film",
    productName: "Crystal Film LED Screen",
    model: "P6.25",
    industry: "retail",
    region: "asia",
    location: "Hong Kong",
    video: `${VID}/case-hongkong-yoga.mp4`,
    poster: `${CASES}/case-hongkong-yoga-studio-p625.jpg`,
    images: [`${CASES}/case-hongkong-yoga-studio-p625.jpg`],
    description:
      "A street-level studio in Hong Kong runs class schedules and ambient motion across its window film — the practice space stays daylit and private behind a screen passers-by can't ignore.",
    featured: false,
  },
  {
    id: "guangxi-bank",
    title: "Bank Branch Glazing",
    product: "crystal-film",
    productName: "Crystal Film LED Screen",
    model: "P6.25",
    industry: "financial",
    region: "asia",
    location: "Guangxi · China",
    video: `${VID}/case-guangxi-bank.mp4`,
    poster: `${CASES}/case-guangxi-bank-p625.jpg`,
    images: [`${CASES}/case-guangxi-bank-p625.jpg`],
    description:
      "Full-height transparent film turns a bank branch's street glazing into a rate board and brand surface — applied straight to the existing glass with no structural work in a working branch.",
    featured: false,
  },
  {
    id: "dongguan-park-facade",
    title: "Technology Park Facade",
    product: "crystal-film",
    productName: "Crystal Film LED Screen",
    model: "P8",
    industry: "corporate",
    region: "asia",
    location: "Dongguan · China",
    video: `${VID}/case-dongguan-park.mp4`,
    poster: `${CASES}/case-dongguan-park-p8.jpg`,
    images: [`${CASES}/case-dongguan-park-p8.jpg`],
    description:
      "A campus building in Dongguan carries large-scale motion graphics across its curtain wall — P8 film keeps the offices behind it bright while the facade reads from across the park.",
    featured: false,
  },
  {
    id: "dongguan-furniture-showroom",
    title: "Furniture Showroom",
    product: "crystal-film",
    productName: "Crystal Film LED Screen",
    model: "P20",
    industry: "exhibition",
    region: "asia",
    location: "Dongguan · China",
    video: `${VID}/case-dongguan-p20.mp4`,
    poster: `${CASES}/case-dongguan-p20-poster.jpg`,
    images: [`${CASES}/case-dongguan-p20-poster.jpg`],
    description:
      "Wide-pitch P20 film spans a furniture showroom's glass frontage — 95% transparency keeps the room sets visible from the street, with brand content floating over them after dark.",
    featured: false,
  },
  {
    id: "sk-retail-corridor",
    title: "SK Retail Corridor",
    product: "crystal-film",
    productName: "Crystal Film LED Screen",
    model: "P6",
    industry: "retail",
    region: "asia",
    location: "China",
    video: `${VID}/case-sk-corridor.mp4`,
    poster: `${CASES}/case-sk-retail-p6.jpg`,
    images: [`${CASES}/case-sk-retail-p6.jpg`],
    description:
      "A retail corridor lined with transparent LED panels — campaign content runs the length of the walkway while each store behind the glass stays in clear view.",
    featured: false,
  },
  {
    id: "maoming-service-area",
    title: "Maoming Expressway Service Area",
    product: "crystal-film",
    productName: "Crystal Film LED Screen",
    model: "P6.25",
    industry: "transportation",
    region: "asia",
    location: "Maoming · China",
    video: `${VID}/case-maomin.mp4`,
    poster: `${CASES}/case-maoming-service-area-p625.jpg`,
    images: [`${CASES}/case-maoming-service-area-p625.jpg`],
    description:
      "The glazed front of the Baiqiao expressway service area doubles as a traveler information and advertising surface — 4K-sourced footage of film applied across the full entrance.",
    featured: false,
  },
  {
    id: "huizhou-commercial",
    title: "Huizhou Commercial Complex",
    product: "crystal-film",
    productName: "Crystal Film LED Screen",
    model: "P10",
    industry: "retail",
    region: "asia",
    location: "Huizhou · China",
    video: `${VID}/case-huizhou-p10.mp4`,
    poster: `${CASES}/case-huizhou-p10-poster.jpg`,
    images: [`${CASES}/case-huizhou-p10-poster.jpg`],
    description:
      "A P10 ribbon wraps the upper glazing of a Huizhou commercial block — full-colour produce and promotion content over the entrance, with the interior daylight untouched.",
    featured: false,
  },
  {
    id: "shop-window-p8",
    title: "Boutique Shop Window",
    product: "crystal-film",
    productName: "Crystal Film LED Screen",
    model: "P8",
    industry: "retail",
    region: "asia",
    location: null,
    video: `${VID}/case-shop-window-p8.mp4`,
    poster: `${CASES}/case-shop-window-p8-poster.jpg`,
    images: [`${CASES}/case-shop-window-p8-poster.jpg`],
    description:
      "A fashion boutique runs celebration content across its window film after hours — the mannequins and shopfloor read straight through the P8 mesh whenever the content rests.",
    featured: false,
  },
  {
    id: "meeting-room-window",
    title: "Conference Room Window",
    product: "crystal-film",
    productName: "Crystal Film LED Screen",
    model: "P8",
    industry: "corporate",
    region: "europe",
    location: null,
    video: `${VID}/case-meeting-room-p8.mp4`,
    poster: `${CASES}/case-meeting-room-p8-poster.jpg`,
    images: [`${CASES}/case-meeting-room-p8-poster.jpg`],
    description:
      "An overseas office turns its meeting-room glazing into a presentation and ambient surface — transparent film on the inside of the glass, video on demand, daylight the rest of the day.",
    featured: false,
  },
  {
    id: "container-showroom",
    title: "Container Pop-Up Showroom",
    product: "crystal-film",
    productName: "Crystal Film LED Screen",
    model: "P8",
    industry: "exhibition",
    region: "asia",
    location: "China",
    video: `${VID}/case-container-p8.mp4`,
    poster: `${CASES}/case-container-p8-poster.jpg`,
    images: [`${CASES}/case-container-p8-poster.jpg`],
    description:
      "A converted shipping container with glass walls becomes a mobile media pavilion — film on every pane plays in sync, and the unit tows to the next venue when the event wraps.",
    featured: false,
  },
  {
    id: "glass-skybridge",
    title: "Glass Skybridge",
    product: "crystal-film",
    productName: "Crystal Film LED Screen",
    model: "P6",
    industry: "corporate",
    region: "asia",
    location: "China",
    video: `${VID}/case-skybridge-p6.mp4`,
    poster: `${CASES}/case-skybridge-p6-poster.jpg`,
    images: [`${CASES}/case-skybridge-p6-poster.jpg`],
    description:
      "An aquarium scene swims the full length of a glazed skybridge at dusk — film along the span turns the link between buildings into the campus's most photographed surface.",
    featured: false,
  },
  {
    id: "round-screen",
    title: "Cylindrical Round Screen",
    product: "crystal-film",
    productName: "Crystal Film LED Screen",
    model: "P6.25",
    industry: "exhibition",
    region: "asia",
    location: "China",
    video: `${VID}/case-round-screen-p625.mp4`,
    poster: `${CASES}/case-round-screen-p625-poster.jpg`,
    images: [`${CASES}/case-round-screen-p625-poster.jpg`],
    description:
      "Flexible film spliced into a full cylinder — content travels seamlessly around the curve, a form factor no rigid panel can follow. The same footage opens the K1 home page.",
    featured: false,
  },
  {
    id: "wuhan-storefront",
    title: "Wuhan Storefront",
    product: "crystal-film",
    productName: "Crystal Film LED Screen",
    model: "P6.25",
    industry: "retail",
    region: "asia",
    location: "Wuhan · China",
    video: `${VID}/case-wuhan.mp4`,
    poster: `${CASES}/case-wuhan-poster.jpg`,
    images: [`${CASES}/case-wuhan-poster.jpg`],
    description:
      "A Wuhan retail unit runs saturated motion content across its glass front — a compact install that shows the film holding colour and brightness in a busy street setting.",
    featured: false,
  },
  {
    id: "beijing-corporate-showroom",
    title: "Beijing Corporate Showroom",
    product: "crystal-film",
    productName: "Crystal Film LED Screen",
    model: "P6.25",
    industry: "corporate",
    region: "asia",
    location: "Beijing · China",
    video: `${VID}/case-beijing-showroom.mp4`,
    poster: `${CASES}/case-beijing-showroom-poster.jpg`,
    images: [`${CASES}/case-beijing-showroom-poster.jpg`],
    description:
      "A corporate exhibition space in Beijing fronts its story wall with transparent LED — visitors read the brand film and the room behind it in one glance.",
    featured: false,
  },
  {
    id: "corporate-showroom-p10",
    title: "Corporate Exhibition Hall",
    product: "crystal-film",
    productName: "Crystal Film LED Screen",
    model: "P10",
    industry: "exhibition",
    region: "asia",
    location: "China",
    video: `${VID}/case-corporate-showroom-p10.mp4`,
    poster: `${CASES}/case-corporate-showroom-p10-poster.jpg`,
    images: [`${CASES}/case-corporate-showroom-p10-poster.jpg`],
    description:
      "P10 film across an enterprise exhibition hall's glazing — wide-pitch transparency keeps the displays behind it legible while the glass carries the headline content.",
    featured: false,
  },

  /* ──────────────────── SMD Holographic Invisible Screen ──────────────────── */
  {
    id: "xinpai-showroom",
    title: "Xinpai Semiconductor Showroom",
    product: "holographic",
    productName: "SMD Holographic Invisible Screen",
    model: "P6.25",
    industry: "exhibition",
    region: "asia",
    location: "Xi'an · China",
    video: `${VID}/case-xinpai.mp4`,
    poster: `${CASES}/case-xinpai-poster.jpg`,
    images: [`${CASES}/case-xinpai-poster.jpg`, `${CASES}/case-xian-xinpai-01.jpg`],
    description:
      "A floor-height holographic screen fronts the Xinpai showroom — a life-size presenter floats on the transparent mesh to greet visitors, while the showroom behind reads straight through the glass.",
    featured: true,
  },
  {
    id: "estee-lauder-shanghai",
    title: "Estée Lauder Flagship",
    product: "holographic",
    productName: "SMD Holographic Invisible Screen",
    model: "P6.25",
    industry: "retail",
    region: "asia",
    location: "Shanghai · China",
    video: `${VID}/case-estee-lauder.mp4`,
    poster: `${CASES}/case-estee-lauder-poster.jpg`,
    images: [
      `${CASES}/case-estee-lauder-poster.jpg`,
      `${CASES}/case-shanghai-estee-lauder-01.jpg`,
      `${CASES}/case-shanghai-estee-lauder-02.jpg`,
    ],
    description:
      "Holographic panels flank the gilded entrance of an Estée Lauder counter in Shanghai — brand films play at eye level as shoppers pass, while the counter behind stays in full view.",
    featured: false,
  },
  {
    id: "baiyun-airport-dream-blue",
    title: "Baiyun Airport — Dream Blue Pavilion",
    product: "holographic",
    productName: "SMD Holographic Invisible Screen",
    model: "P6.25",
    industry: "transportation",
    region: "asia",
    location: "Guangzhou · China",
    video: `${VID}/case-baiyun-airport.mp4`,
    poster: `${CASES}/case-baiyun-airport-poster.jpg`,
    images: [
      `${CASES}/case-baiyun-airport-poster.jpg`,
      `${CASES}/case-guangzhou-baiyun-airport-01.jpg`,
      `${CASES}/case-guangzhou-baiyun-airport-02.jpg`,
      `${CASES}/case-guangzhou-baiyun-airport-03.jpg`,
    ],
    description:
      "Holographic panels wrap the Dream Blue store at Guangzhou Baiyun Airport in deep-blue brand content that reads far down the concourse — while the bottle displays stay clearly visible straight through the mesh.",
    featured: true,
  },
  {
    id: "macau-starworld",
    title: "StarWorld Hotel & Casino",
    product: "holographic",
    productName: "SMD Holographic Invisible Screen",
    model: "P6 Crystal Screen",
    industry: "entertainment",
    region: "asia",
    location: "Macau",
    video: `${VID}/case-macau.mp4`,
    poster: `${CASES}/macau-casino-01.jpg`,
    images: [`${CASES}/macau-casino-01.jpg`, `${CASES}/macau-casino-02.jpg`],
    description:
      "A P6.0 crystal-screen installation at Macau's StarWorld — a large curved indoor wall whose high-brightness content holds its own against a dense, lit casino interior while keeping sightlines open.",
    featured: false,
  },
  {
    id: "cambodia-lasvegas-sun",
    title: "Las Vegas Sun Casino",
    product: "holographic",
    productName: "SMD Holographic Invisible Screen",
    model: null,
    industry: "entertainment",
    region: "asia",
    location: "Bavet · Cambodia",
    video: `${VID}/case-cambodia-casino.mp4`,
    poster: `${CASES}/case-cambodia-casino-poster.jpg`,
    images: [
      `${CASES}/case-cambodia-casino-poster.jpg`,
      `${CASES}/case-cambodia-lasvegas-sun-01.jpg`,
      `${CASES}/case-cambodia-lasvegas-sun-02.jpg`,
    ],
    description:
      "A sweeping curved holographic LED wall anchors the gaming floor of the Las Vegas Sun — resort and entertainment content carries across the room at a brightness that holds up against a fully lit casino interior.",
    featured: false,
  },
  {
    id: "changchun-optoelectronics",
    title: "Changchun Optoelectronics Park",
    product: "holographic",
    productName: "SMD Holographic Invisible Screen",
    model: "Crystal Screen",
    industry: "corporate",
    region: "asia",
    location: "Changchun · China",
    video: `${VID}/case-changchun.mp4`,
    poster: `${CASES}/changchun-01.jpg`,
    images: [`${CASES}/changchun-01.jpg`, `${CASES}/changchun-02.jpg`, `${CASES}/changchun-03.jpg`],
    description:
      "A transparent media facade wrapping the campus atrium — daylight passes through by day, motion graphics read clearly after dark, and the concourse glazing carries live content without ever blocking the view.",
    featured: false,
  },
  {
    id: "hefei-postal-bank",
    title: "Wanda Plaza — Postal Savings Bank",
    product: "holographic",
    productName: "SMD Holographic Invisible Screen",
    model: "Crystal Screen",
    industry: "financial",
    region: "asia",
    location: "Hefei · China",
    video: `${VID}/case-hefei-bank.mp4`,
    poster: `${CASES}/case-hefei-bank-poster.jpg`,
    images: [
      `${CASES}/case-hefei-bank-poster.jpg`,
      `${CASES}/case-hefei-postal-bank-02.jpg`,
      `${CASES}/case-hefei-postal-bank-03.jpg`,
      `${CASES}/case-hefei-postal-bank-04.jpg`,
    ],
    description:
      "Crystal-screen panels sit just behind the glazing of a Postal Savings Bank branch at Hefei Wanda — saturated blue brand animation visible from the street, with the banking hall kept bright and open behind it.",
    featured: false,
  },
  {
    id: "nanning-zhongguangshi",
    title: "Zhongguangshi Media Center",
    product: "holographic",
    productName: "SMD Holographic Invisible Screen",
    model: "P6.25",
    industry: "corporate",
    region: "asia",
    location: "Nanning · China",
    video: `${VID}/case-nanning.mp4`,
    poster: `${CASES}/case-nanning-poster.jpg`,
    images: [
      `${CASES}/case-nanning-poster.jpg`,
      `${CASES}/case-nanning-zhongguangshi-01.jpg`,
      `${CASES}/case-nanning-zhongguangshi-02.jpg`,
    ],
    description:
      "A front-mounted holographic screen follows the curved corner glazing of Zhongguangshi's Nanning offices — koi and water imagery swim across the facade at dusk, added to the existing glass without rebuilding it.",
    featured: false,
  },
  {
    id: "mashan-resort",
    title: "Mashan Tourism Resort",
    product: "holographic",
    productName: "SMD Holographic Invisible Screen",
    model: null,
    industry: "hospitality",
    region: "asia",
    location: "Mashan · China",
    video: `${VID}/case-mashan.mp4`,
    poster: `${CASES}/mashan-video.jpg`,
    images: [`${CASES}/mashan-video.jpg`, `${CASES}/mashan-01.jpg`, `${CASES}/mashan-02.jpg`],
    description:
      "An indoor holographic surface follows the resort's organic architecture, turning a sculpted wall into a calm, ambient light feature that bends where a rigid panel never could.",
    featured: false,
  },
  {
    id: "immersive-tunnel",
    title: "Immersive LED Tunnel",
    product: "holographic",
    productName: "SMD Holographic Invisible Screen",
    model: null,
    industry: "entertainment",
    region: "asia",
    location: null,
    video: `${VID}/case-immersive-tunnel.mp4`,
    poster: `${CASES}/case-immersive-tunnel-poster.jpg`,
    images: [
      `${CASES}/case-immersive-tunnel-poster.jpg`,
      `${CASES}/case-immersive-tunnel-01.jpg`,
      `${CASES}/case-immersive-tunnel-02.jpg`,
      `${CASES}/case-immersive-tunnel-03.jpg`,
    ],
    description:
      "An LED-lined corridor turns a simple walkway into an immersive environment — bubble animations drift across both walls and overhead, wrapping visitors in colour from entry to exit.",
    featured: false,
  },
  {
    id: "corporate-lobby-wave",
    title: "Corporate Lobby Glass Wall",
    product: "holographic",
    productName: "SMD Holographic Invisible Screen",
    model: null,
    industry: "corporate",
    region: "asia",
    location: null,
    video: `${VID}/case-holo-lobby-wave.mp4`,
    poster: `${CASES}/case-holo-lobby-wave-poster.jpg`,
    images: [`${CASES}/case-holo-lobby-wave-poster.jpg`],
    description:
      "A particle wave rolls across the glass wall behind a reception desk — the lobby reads as architecture first and a screen second, exactly what the invisible mesh is for.",
    featured: false,
  },
  {
    id: "auto-dealership-showroom",
    title: "Auto Dealership Showroom",
    product: "holographic",
    productName: "SMD Holographic Invisible Screen",
    model: null,
    industry: "automotive",
    region: "asia",
    location: null,
    video: `${VID}/case-holo-auto-showroom.mp4`,
    poster: `${CASES}/case-holo-auto-showroom-poster.jpg`,
    images: [`${CASES}/case-holo-auto-showroom-poster.jpg`],
    description:
      "A band of holographic mesh runs above the showroom floor — launch content plays over the cars without hiding a single vehicle from the street.",
    featured: false,
  },
  {
    id: "sculpture-gallery",
    title: "Sculpture Gallery Screen",
    product: "holographic",
    productName: "SMD Holographic Invisible Screen",
    model: null,
    industry: "exhibition",
    region: "asia",
    location: null,
    video: `${VID}/case-holo-exhibition.mp4`,
    poster: `${CASES}/case-holo-exhibition-poster.jpg`,
    images: [`${CASES}/case-holo-exhibition-poster.jpg`],
    description:
      "A gallery fronts its white sculpture installation with transparent mesh — projected seasons drift over the artwork, and the pieces stay perfectly visible through the screen.",
    featured: false,
  },
  {
    id: "aquarium-storefront",
    title: "Aquarium Storefront Window",
    product: "holographic",
    productName: "SMD Holographic Invisible Screen",
    model: null,
    industry: "retail",
    region: "asia",
    location: null,
    video: `${VID}/case-holo-aquarium-window.mp4`,
    poster: `${CASES}/case-holo-aquarium-window-poster.jpg`,
    images: [`${CASES}/case-holo-aquarium-window-poster.jpg`],
    description:
      "A street-front window becomes an aquarium after dark — deep-blue underwater content floats on the glass while foot traffic slows to watch.",
    featured: false,
  },
  {
    id: "heritage-facade",
    title: "Heritage Building Facade",
    product: "holographic",
    productName: "SMD Holographic Invisible Screen",
    model: null,
    industry: "entertainment",
    region: "asia",
    location: null,
    video: `${VID}/case-holo-heritage-facade.mp4`,
    poster: `${CASES}/case-holo-heritage-facade-poster.jpg`,
    images: [`${CASES}/case-holo-heritage-facade-poster.jpg`],
    description:
      "Transparent mesh spans the glazed front of an ornate cultural venue — evening content plays across the facade without touching the architecture behind it.",
    featured: false,
  },
  {
    id: "jellyfish-window",
    title: "Jellyfish Window Display",
    product: "holographic",
    productName: "SMD Holographic Invisible Screen",
    model: null,
    industry: "retail",
    region: "asia",
    location: null,
    video: `${VID}/case-holo-jellyfish.mp4`,
    poster: `${CASES}/case-holo-jellyfish-poster.jpg`,
    images: [`${CASES}/case-holo-jellyfish-poster.jpg`],
    description:
      "Luminous jellyfish drift across a glass partition — the kind of floating, depth-rich content the holographic mesh renders best.",
    featured: false,
  },
  {
    id: "exhibition-glass-cylinder",
    title: "Wraparound Glass Cylinder",
    product: "holographic",
    productName: "SMD Holographic Invisible Screen",
    model: null,
    industry: "exhibition",
    region: "asia",
    location: null,
    video: `${VID}/case-holo-boutique-window.mp4`,
    poster: `${CASES}/case-holo-boutique-window-poster.jpg`,
    images: [`${CASES}/case-holo-boutique-window-poster.jpg`],
    description:
      "Holographic mesh wraps a full glass cylinder on an exhibition floor — content circles the drum without a visible seam, and the room reads straight through it between scenes.",
    featured: false,
  },
  {
    id: "youtang-plaza",
    title: "Youtang Plaza Curved Screen",
    product: "holographic",
    productName: "SMD Holographic Invisible Screen",
    model: null,
    industry: "retail",
    region: "asia",
    location: "China",
    video: `${VID}/case-holo-curved-mall.mp4`,
    poster: `${CASES}/case-holo-curved-mall-poster.jpg`,
    images: [`${CASES}/case-holo-curved-mall-poster.jpg`],
    description:
      "Mesh panels follow the rounded corner of Youtang Plaza's glass facade — one continuous image bends around the building where flat panels would have to break.",
    featured: false,
  },

  /* ──────────────────────────── Soft LED Display ──────────────────────────── */
  {
    id: "storefront-window-loop",
    title: "Storefront Window Loop",
    product: "soft-led-display",
    productName: "Soft LED Display",
    model: "XL 70″",
    industry: "retail",
    region: "americas",
    location: "North America",
    video: `${VID}/matrix-panel-demo-01.mp4`,
    poster: `${MATRIX}/scenario-smoke-shop.jpg`,
    images: [`${MATRIX}/scenario-smoke-shop.jpg`],
    description:
      "A 70-inch soft panel scrolls offers in a smoke-shop window — stuck to the glass, powered over USB, and reprogrammed from the counter between customers.",
    featured: false,
  },
  {
    id: "bar-lounge-promos",
    title: "Bar & Lounge Promos",
    product: "soft-led-display",
    productName: "Soft LED Display",
    model: "L 52″",
    industry: "hospitality",
    region: "americas",
    location: "North America",
    video: `${VID}/matrix-panel-demo-02.mp4`,
    poster: `${MATRIX}/scenario-bar-lounge.jpg`,
    images: [`${MATRIX}/scenario-bar-lounge.jpg`],
    description:
      "Happy-hour specials and music-reactive effects behind the bar — a 52-inch flexible sign that changes with the night's program from a phone.",
    featured: false,
  },
  {
    id: "pixel-art-animations",
    title: "Pixel Art & Animations",
    product: "soft-led-display",
    productName: "Soft LED Display",
    model: "M 35″",
    industry: "retail",
    region: "americas",
    location: "North America",
    video: `${VID}/matrix-panel-demo-03.mp4`,
    poster: `${MATRIX}/scenario-vape-shop.jpg`,
    images: [`${MATRIX}/scenario-vape-shop.jpg`],
    description:
      "DIY pixel art and template animations from the iPixel Color library — the 35-inch panel as a storefront mood piece, not just a message board.",
    featured: false,
  },
  {
    id: "grocery-liquor-store",
    title: "Grocery & Liquor Store",
    product: "soft-led-display",
    productName: "Soft LED Display",
    model: null,
    industry: "retail",
    region: "americas",
    location: "North America",
    video: `${VID}/case-grocery-liquor.mp4`,
    poster: `${CASES}/case-grocery-liquor-poster.jpg`,
    images: [`${CASES}/case-grocery-liquor-poster.jpg`],
    description:
      "A neighborhood grocery-liquor store runs specials over the register — one panel, one outlet, and the week's deals change as fast as the owner can type them.",
    featured: false,
  },
  {
    id: "jewelry-store-display",
    title: "Jewelry Store Display",
    product: "soft-led-display",
    productName: "Soft LED Display",
    model: null,
    industry: "retail",
    region: "americas",
    location: "North America",
    video: `${VID}/case-jewelry-store.mp4`,
    poster: `${CASES}/case-jewelry-store-poster.jpg`,
    images: [`${CASES}/case-jewelry-store-poster.jpg`],
    description:
      "A jeweler's window picks up a scrolling accent sign — bright enough to read from across the street, gentle enough to keep the cases as the hero.",
    featured: false,
  },
  {
    id: "realtor-agency-window",
    title: "Realtor Agency Window",
    product: "soft-led-display",
    productName: "Soft LED Display",
    model: null,
    industry: "corporate",
    region: "americas",
    location: "North America",
    video: `${VID}/case-realtor.mp4`,
    poster: `${CASES}/case-realtor-poster.jpg`,
    images: [`${CASES}/case-realtor-poster.jpg`],
    description:
      "New listings and open-house hours scroll in a realtor's front window — updated from the app each morning without touching the display.",
    featured: false,
  },
  {
    id: "wireless-accessories-store",
    title: "Wireless & Accessories Store",
    product: "soft-led-display",
    productName: "Soft LED Display",
    model: null,
    industry: "retail",
    region: "americas",
    location: "North America",
    video: `${VID}/case-accessories-store.mp4`,
    poster: `${CASES}/case-accessories-store-poster.jpg`,
    images: [`${CASES}/case-accessories-store-poster.jpg`],
    description:
      "A wholesale-retail wireless shop strings a soft panel along its window line — repairs, plans, and trade-in offers on rotation all day.",
    featured: false,
  },
  {
    id: "liquor-store-sign",
    title: "Liquor Store Sign",
    product: "soft-led-display",
    productName: "Soft LED Display",
    model: null,
    industry: "retail",
    region: "americas",
    location: "North America",
    video: `${VID}/case-liquor-store.mp4`,
    poster: `${CASES}/case-liquor-store-poster.jpg`,
    images: [`${CASES}/case-liquor-store-poster.jpg`],
    description:
      "Beer, liquor, wine — and tonight's deal — on a flexible matrix sign above the aisles, switched from the counter with the bundled remote.",
    featured: false,
  },
  {
    id: "pool-hall-bar",
    title: "Pool Hall & Bar",
    product: "soft-led-display",
    productName: "Soft LED Display",
    model: null,
    industry: "entertainment",
    region: "americas",
    location: "North America",
    video: `${VID}/case-pool-hall.mp4`,
    poster: `${CASES}/case-pool-hall-poster.jpg`,
    images: [`${CASES}/case-pool-hall-poster.jpg`],
    description:
      "A pool hall sets the mood with colour-cycling welcome text over the tables — ambient signage that runs on ten watts, every night of the week.",
    featured: false,
  },
  {
    id: "neighborhood-grocer",
    title: "Neighborhood Grocer",
    product: "soft-led-display",
    productName: "Soft LED Display",
    model: null,
    industry: "retail",
    region: "americas",
    location: "North America",
    video: `${VID}/case-grocers.mp4`,
    poster: `${CASES}/case-grocers-poster.jpg`,
    images: [`${CASES}/case-grocers-poster.jpg`],
    description:
      "Sizes, prices, and daily stock on a soft panel over the snack wall — a corner grocer's answer to reprinting shelf signs.",
    featured: false,
  },
];

/** Projects flagged as flagship installs (grid sorts these to the front). */
export function getFeaturedProjects() {
  return PROJECTS.filter((p) => p.featured);
}

/** Look up a single project by id. */
export function getProject(id) {
  return PROJECTS.find((p) => p.id === id) || null;
}

/** Label helpers for badges/tags. */
export const INDUSTRY_LABEL = Object.fromEntries(
  INDUSTRIES.map(({ value, label }) => [value, label])
);
export const REGION_LABEL = Object.fromEntries(
  REGIONS.map(({ value, label }) => [value, label])
);
export const PRODUCT_TYPE_LABEL = Object.fromEntries(
  PRODUCT_TYPES.map(({ value, label }) => [value, label])
);
